import type { CommunityRequest, MissionTask, Volunteer } from "@/lib/types";

export const requests: CommunityRequest[] = [
  {
    id: "REQ-1001",
    title: "Flooded settlement near Mithi River needs evacuation and food",
    city: "Mumbai",
    ward: "Kurla L",
    category: "Disaster",
    peopleAffected: 420,
    severity: 10,
    vulnerability: 9,
    waitHours: 5,
    repeatedReports: 12,
    weatherRisk: 10,
    povertyIndex: 8,
    lat: 19.0728,
    lng: 72.8826,
    source: "WhatsApp",
    priorityScore: 98,
    explanation: ["High flood risk", "Large affected population", "Repeated local reports", "High vulnerability"]
  },
  {
    id: "REQ-1002",
    title: "Medicine stockout for seniors in Dharavi clinic",
    city: "Mumbai",
    ward: "Dharavi",
    category: "Health",
    peopleAffected: 85,
    severity: 9,
    vulnerability: 10,
    waitHours: 18,
    repeatedReports: 5,
    weatherRisk: 3,
    povertyIndex: 9,
    lat: 19.038,
    lng: 72.8538,
    source: "Field App",
    priorityScore: 88,
    explanation: ["Senior citizen risk", "Critical medicine shortage", "Long waiting time"]
  },
  {
    id: "REQ-1003",
    title: "After-school learning support requested for municipal school",
    city: "Pune",
    ward: "Yerawada",
    category: "Education",
    peopleAffected: 60,
    severity: 5,
    vulnerability: 6,
    waitHours: 72,
    repeatedReports: 3,
    weatherRisk: 1,
    povertyIndex: 7,
    lat: 18.5523,
    lng: 73.899,
    source: "CSV",
    priorityScore: 52,
    explanation: ["Important but non-emergency", "Moderate vulnerability", "Good candidate for scheduled volunteers"]
  },
  {
    id: "REQ-1004",
    title: "Community kitchen reports 1,200 meal shortage",
    city: "Delhi",
    ward: "Yamuna Pushta",
    category: "Food",
    peopleAffected: 1200,
    severity: 8,
    vulnerability: 8,
    waitHours: 9,
    repeatedReports: 9,
    weatherRisk: 6,
    povertyIndex: 8,
    lat: 28.6556,
    lng: 77.241,
    source: "OCR",
    priorityScore: 91,
    explanation: ["Large food gap", "High poverty index", "Multiple duplicate-confirmed reports"]
  }
];

export const volunteers: Volunteer[] = [
  {
    id: "VOL-201",
    name: "Aarav Menon",
    city: "Mumbai",
    lat: 19.076,
    lng: 72.8777,
    verifiedSkills: ["First Aid", "Driving", "Flood Rescue", "Logistics"],
    languages: ["Hindi", "Marathi", "English"],
    availabilityHours: 8,
    reliabilityScore: 94,
    missionsCompleted: 41,
    certifications: ["Red Cross First Aid", "SevaSync Flood Response Verified"],
    interests: ["Disaster", "Health"],
    trustBadge: "Crisis Ready"
  },
  {
    id: "VOL-202",
    name: "Sana Qureshi",
    city: "Mumbai",
    lat: 19.041,
    lng: 72.855,
    verifiedSkills: ["Nursing", "First Aid", "Counseling", "Senior Care"],
    languages: ["Hindi", "Marathi", "Urdu"],
    availabilityHours: 5,
    reliabilityScore: 91,
    missionsCompleted: 34,
    certifications: ["BSc Nursing", "SevaSync Medical Camp Verified"],
    interests: ["Health", "Senior Care"],
    trustBadge: "Lead"
  },
  {
    id: "VOL-203",
    name: "Ishita Rao",
    city: "Pune",
    lat: 18.55,
    lng: 73.89,
    verifiedSkills: ["Teaching", "Childcare", "Translation", "Event Management"],
    languages: ["Marathi", "Hindi", "English"],
    availabilityHours: 6,
    reliabilityScore: 87,
    missionsCompleted: 22,
    certifications: ["SevaSync Teaching Foundations"],
    interests: ["Education", "Childcare"],
    trustBadge: "Reliable"
  },
  {
    id: "VOL-204",
    name: "Kabir Batra",
    city: "Delhi",
    lat: 28.651,
    lng: 77.233,
    verifiedSkills: ["Food Distribution", "Driving", "Inventory", "Logistics"],
    languages: ["Hindi", "Punjabi", "English"],
    availabilityHours: 10,
    reliabilityScore: 89,
    missionsCompleted: 30,
    certifications: ["Commercial Driving", "SevaSync Logistics Verified"],
    interests: ["Food", "Disaster"],
    trustBadge: "Lead"
  }
];

export const tasks: MissionTask[] = [
  {
    id: "TASK-501",
    requestId: "REQ-1001",
    title: "Dispatch rescue and relief team to Kurla",
    requiredSkills: ["Flood Rescue", "First Aid", "Driving", "Logistics"],
    requiredLanguages: ["Hindi", "Marathi"],
    urgency: 10,
    city: "Mumbai",
    status: "Assigned",
    etaMinutes: 22,
    assignedVolunteerIds: ["VOL-201"]
  },
  {
    id: "TASK-502",
    requestId: "REQ-1002",
    title: "Run senior medicine support desk",
    requiredSkills: ["Nursing", "Senior Care", "Counseling"],
    requiredLanguages: ["Hindi", "Marathi"],
    urgency: 9,
    city: "Mumbai",
    status: "Open",
    etaMinutes: 14,
    assignedVolunteerIds: []
  },
  {
    id: "TASK-503",
    requestId: "REQ-1003",
    title: "Create teaching cohort for evening classes",
    requiredSkills: ["Teaching", "Childcare", "Translation"],
    requiredLanguages: ["Marathi"],
    urgency: 5,
    city: "Pune",
    status: "Open",
    etaMinutes: 18,
    assignedVolunteerIds: []
  },
  {
    id: "TASK-504",
    requestId: "REQ-1004",
    title: "Move dry ration kits to Yamuna Pushta kitchen",
    requiredSkills: ["Food Distribution", "Driving", "Inventory", "Logistics"],
    requiredLanguages: ["Hindi"],
    urgency: 9,
    city: "Delhi",
    status: "In Progress",
    etaMinutes: 31,
    assignedVolunteerIds: ["VOL-204"]
  }
];
