COMMUNITY_REQUESTS = [
    {
        "id": "REQ-1001",
        "title": "Flooded settlement near Mithi River needs evacuation and food",
        "city": "Mumbai",
        "ward": "Kurla L",
        "category": "Disaster",
        "people_affected": 420,
        "severity": 10,
        "vulnerability": 9,
        "wait_hours": 5,
        "repeated_reports": 12,
        "weather_risk": 10,
        "poverty_index": 8,
        "lat": 19.0728,
        "lng": 72.8826,
        "source": "WhatsApp",
        "priority_score": 98,
    },
    {
        "id": "REQ-1002",
        "title": "Medicine stockout for seniors in Dharavi clinic",
        "city": "Mumbai",
        "ward": "Dharavi",
        "category": "Health",
        "people_affected": 85,
        "severity": 9,
        "vulnerability": 10,
        "wait_hours": 18,
        "repeated_reports": 5,
        "weather_risk": 3,
        "poverty_index": 9,
        "lat": 19.038,
        "lng": 72.8538,
        "source": "Field App",
        "priority_score": 88,
    },
]

VOLUNTEERS = [
    {
        "id": "VOL-201",
        "name": "Aarav Menon",
        "city": "Mumbai",
        "lat": 19.076,
        "lng": 72.8777,
        "verified_skills": ["First Aid", "Driving", "Flood Rescue", "Logistics"],
        "languages": ["Hindi", "Marathi", "English"],
        "availability_hours": 8,
        "reliability_score": 94,
        "missions_completed": 41,
        "certifications": ["Red Cross First Aid", "SevaSync Flood Response Verified"],
        "trust_badge": "Crisis Ready",
    },
    {
        "id": "VOL-202",
        "name": "Sana Qureshi",
        "city": "Mumbai",
        "lat": 19.041,
        "lng": 72.855,
        "verified_skills": ["Nursing", "First Aid", "Counseling", "Senior Care"],
        "languages": ["Hindi", "Marathi", "Urdu"],
        "availability_hours": 5,
        "reliability_score": 91,
        "missions_completed": 34,
        "certifications": ["BSc Nursing", "SevaSync Medical Camp Verified"],
        "trust_badge": "Lead",
    },
]

TASKS = [
    {
        "id": "TASK-501",
        "request_id": "REQ-1001",
        "title": "Dispatch rescue and relief team to Kurla",
        "required_skills": ["Flood Rescue", "First Aid", "Driving", "Logistics"],
        "required_languages": ["Hindi", "Marathi"],
        "urgency": 10,
        "city": "Mumbai",
        "status": "Assigned",
    },
    {
        "id": "TASK-502",
        "request_id": "REQ-1002",
        "title": "Run senior medicine support desk",
        "required_skills": ["Nursing", "Senior Care", "Counseling"],
        "required_languages": ["Hindi", "Marathi"],
        "urgency": 9,
        "city": "Mumbai",
        "status": "Open",
    },
]
